#!/bin/bash
# ===========================================
# CPQ System Production Initialization Guide
# ===========================================

echo "=== CPQ 报价系统 Production Initialization ==="
echo ""
echo "Prerequisites:"
echo "  - Java 17+"
echo "  - Node.js 24+"
echo "  - PostgreSQL 16 running"
echo "  - Docker (for development)"
echo ""
echo "Default admin account:"
echo "  Username: admin"
echo "  Password: Admin@2026 (force change on first login)"
echo ""
echo "Pre-configured data:"
echo "  Regions: 华南, 华东, 华北, 华中"
echo "  Departments: 销售一部, 销售二部, 销售三部"
echo "  Processes: 27 pre-configured across 6 categories"
echo ""
echo "Configuration (application.properties):"
echo "  SMTP: quarkus.mailer.* (set mock=false for production)"
echo "  Encryption key: cpq.encryption-key (change for production)"
echo "  Session: In-memory (single instance deployment only)"
echo "  Database: quarkus.datasource.* (update for production)"
echo ""
echo "Start development:"
echo "  1. docker-compose -f cpq-backend/docker-compose.yml up -d"
echo "  2. cd cpq-backend && ./mvnw quarkus:dev"
echo "  3. cd cpq-frontend && npm install && npm run dev"
echo ""
echo "URLs:"
echo "  Backend API: http://localhost:8081/api/cpq/"
echo "  Frontend:    http://localhost:5174/"
echo ""
echo "Test suite: cd cpq-backend && ./mvnw test"
