 WITH cust_scope AS (
         SELECT DISTINCT cp.customer_no,
            cp.material_no
           FROM ds_quote_customer_part cp
          WHERE cp.material_no IS NOT NULL
        UNION
         SELECT DISTINCT cp.customer_no,
            b.input_material_no AS material_no
           FROM ds_quote_customer_part cp
             JOIN ds_quote_material_bom b ON b.material_no::text = cp.material_no::text
          WHERE cp.material_no IS NOT NULL AND b.input_material_no IS NOT NULL
        )
 SELECT v.id,
    v.system_type,
    v.customer_no,
    v.material_no,
    v.characteristic,
    v.component_no,
    v.part_no,
    v.effective_datetime,
    v.expire_datetime,
    v.operation_no,
    v.operation_seq,
    v.seq_no,
    v.issue_unit,
    v.composition_qty,
    v.base_qty,
    v.component_usage_type,
    v.feature_mgmt,
    v.content,
    v.upper_limit_pct,
    v.lower_limit_pct,
    v.scrap_batch,
    v.scrap_rate,
    v.defect_rate,
    v.fixed_scrap,
    v.issue_location,
    v.issue_storage,
    v.fas_group,
    v.plug_position,
    v.ref_rd_center,
    v.is_optional,
    v.wo_expand_option,
    v.is_purchase_replace,
    v.component_lead_time,
    v.main_substitute,
    v.attached_part,
    v.ecn_no,
    v.use_qty_formula,
    v.qty_formula,
    v.scrap_rate_type,
    v.is_backflush,
    v.is_customer_supply,
    v.recovery_discount,
    v.recovery_currency,
    v.recovery_unit,
    v.created_at,
    v.updated_at,
    v.created_by,
    v.updated_by,
    v.hf_part_no,
    v.is_current,
    v.production_no,
    v.material_part_no,
    v.pending_quotation_id,
    v.pending_supersedes
   FROM element_bom_item v
UNION ALL
 SELECT md5((('dqeb:'::text || e.id::text) || ':'::text) || e.customer_no::text)::uuid AS id,
    'QUOTE'::character varying(10) AS system_type,
    e.customer_no,
    e.material_no::character varying(20) AS material_no,
    '2000'::character varying(100) AS characteristic,
    e.element_code::character varying(20) AS component_no,
    NULL::character varying(20) AS part_no,
    NULL::timestamp(6) with time zone AS effective_datetime,
    NULL::timestamp(6) with time zone AS expire_datetime,
    NULL::character varying(20) AS operation_no,
    NULL::character varying(20) AS operation_seq,
    e.item_seq AS seq_no,
    NULL::character varying(20) AS issue_unit,
    NULL::numeric(24,12) AS composition_qty,
    NULL::numeric(24,12) AS base_qty,
    NULL::character varying(100) AS component_usage_type,
    NULL::character varying(20) AS feature_mgmt,
    e.content_pct::numeric(24,12) AS content,
    NULL::numeric(18,12) AS upper_limit_pct,
    NULL::numeric(18,12) AS lower_limit_pct,
    NULL::numeric(24,12) AS scrap_batch,
    NULL::numeric(18,12) AS scrap_rate,
    NULL::numeric(18,12) AS defect_rate,
    NULL::numeric(24,12) AS fixed_scrap,
    NULL::character varying(50) AS issue_location,
    NULL::character varying(50) AS issue_storage,
    NULL::character varying(20) AS fas_group,
    NULL::character varying(50) AS plug_position,
    NULL::character varying(50) AS ref_rd_center,
    NULL::boolean AS is_optional,
    NULL::character varying(20) AS wo_expand_option,
    NULL::boolean AS is_purchase_replace,
    NULL::numeric(24,12) AS component_lead_time,
    NULL::character varying(20) AS main_substitute,
    NULL::character varying(20) AS attached_part,
    NULL::character varying(30) AS ecn_no,
    NULL::boolean AS use_qty_formula,
    NULL::character varying(500) AS qty_formula,
    NULL::character varying(20) AS scrap_rate_type,
    NULL::boolean AS is_backflush,
    NULL::boolean AS is_customer_supply,
    NULL::numeric(18,12) AS recovery_discount,
    NULL::character varying(10) AS recovery_currency,
    NULL::character varying(20) AS recovery_unit,
    e.created_at::timestamp(6) with time zone AS created_at,
    COALESCE(e.updated_at, e.created_at)::timestamp(6) with time zone AS updated_at,
    NULL::uuid AS created_by,
    NULL::uuid AS updated_by,
    e.material_no::character varying(20) AS hf_part_no,
    true AS is_current,
    NULL::character varying(32) AS production_no,
    e.material_part_no::character varying(32) AS material_part_no,
    NULL::uuid AS pending_quotation_id,
    NULL::uuid[] AS pending_supersedes
   FROM ds_quote_element_bom e
  WHERE (EXISTS ( SELECT 1
           FROM cust_scope cs
          WHERE cs.material_no::text = e.material_no::text)) AND NOT (EXISTS ( SELECT 1
           FROM element_bom_item x
          WHERE x.system_type::text = 'QUOTE'::text AND x.is_current AND x.material_no::text = e.material_no::text AND x.customer_no::text = e.customer_no::text));
